name: Build and deploy container app - gianmichelesiano

on:
  push:
    branches: 
      - main
  workflow_dispatch:
    
jobs:

  build:
    runs-on: ubuntu-latest
  
    steps:
      - uses: actions/checkout@v3
    
      - name: Login container registry
        uses: docker/login-action@v1
        with:
          registry: https://index.docker.io/v1/
          username: ${{ secrets.ContainesUsername }} 
          password: ${{ secrets.ContainesPassword }} 

      - name: Build and push container image
        uses: docker/build-push-action@v2
        with:
          context: ./
          push: True
          tags: index.docker.io/${{ secrets.ContainesUsername }}/testcicd1:${{ github.sha }}
          file: ./Dockerfile

  deploy:
    runs-on: ubuntu:latest
    needs: build
    environment:
      name: 'production'
      url: ${{ steps.deploy-to-webapp.outputs-webapp-url }}
    
    steps:
      - name: Deploy to azure 
        id: deploy-to-webapp
        uses: azure/webapps@v2
        with:
          app-name: 'gianmicheletestcicd'
          slot-name: 'production'
          publish-profile: ${{ secrets.PublishProfile }}
          image: 'index.docker.io/${{ secrets.ContainesUsername }}/testcicd1:${{ github.sha }}'
  
